<a href="https://colab.research.google.com/github/Kunalthebug/Deep-Learning/blob/master/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn,length=len(uploaded[fn])))

Saving iris.data to iris.data
User uploaded file "iris.data" with length 4551 bytes


In [3]:
import pandas as pd
import io
data=pd.read_csv(io.StringIO(uploaded['iris.data'].decode('utf-8')))
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot 
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np


In [6]:
dataset=pd.read_csv('iris.data')
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [0]:
X=data.iloc[:,0:4].values
y=data.iloc[:,4].values


In [0]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y1=encoder.fit_transform(y)
Y=pd.get_dummies(y1).values

In [0]:
#splitting the dataset into training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.20,shuffle=True)


In [11]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [0]:
model=Sequential()
#input layer
model.add(Dense(4,input_shape=(4,),activation='relu'))
#hidden layer
model.add(Dense(4,input_shape=(4,),activation='relu'))
#output layer
model.add(Dense(3,activation='sigmoid'))

In [0]:
model.compile(optimizer="Adam",loss='categorical_crossentropy',metrics=['accuracy'])

In [23]:
model.fit(X_train,y_train,batch_size=10,nb_epoch=300)

Epoch 1/300
119/119 [==============================] - 0s 201us/step - loss: 0.7506 - accuracy: 0.6471
Epoch 2/300
119/119 [==============================] - 0s 153us/step - loss: 0.7475 - accuracy: 0.6471
Epoch 3/300
119/119 [==============================] - 0s 150us/step - loss: 0.7443 - accuracy: 0.6471
Epoch 4/300
119/119 [==============================] - 0s 150us/step - loss: 0.7412 - accuracy: 0.6471
Epoch 5/300
119/119 [==============================] - 0s 151us/step - loss: 0.7384 - accuracy: 0.6471
Epoch 6/300
119/119 [==============================] - 0s 158us/step - loss: 0.7355 - accuracy: 0.6471
Epoch 7/300
119/119 [==============================] - 0s 150us/step - loss: 0.7327 - accuracy: 0.6471
Epoch 8/300
119/119 [==============================] - 0s 138us/step - loss: 0.7301 - accuracy: 0.6471
Epoch 9/300
119/119 [==============================] - 0s 148us/step - loss: 0.7277 - accuracy: 0.6471
Epoch 10/300
 10/119 [=>............................] - ETA: 0s - loss: 0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


119/119 [==============================] - 0s 165us/step - loss: 0.7251 - accuracy: 0.6471
Epoch 11/300
119/119 [==============================] - 0s 166us/step - loss: 0.7224 - accuracy: 0.6471
Epoch 12/300
119/119 [==============================] - 0s 152us/step - loss: 0.7203 - accuracy: 0.6471
Epoch 13/300
119/119 [==============================] - 0s 151us/step - loss: 0.7171 - accuracy: 0.6471
Epoch 14/300
119/119 [==============================] - 0s 152us/step - loss: 0.7151 - accuracy: 0.6471
Epoch 15/300
119/119 [==============================] - 0s 154us/step - loss: 0.7133 - accuracy: 0.6471
Epoch 16/300
119/119 [==============================] - 0s 164us/step - loss: 0.7095 - accuracy: 0.6471
Epoch 17/300
119/119 [==============================] - 0s 170us/step - loss: 0.7071 - accuracy: 0.6471
Epoch 18/300
119/119 [==============================] - 0s 224us/step - loss: 0.7050 - accuracy: 0.6471
Epoch 19/300
119/119 [==============================] - 0s 153us/step - loss:

In [0]:
#predicting the test values
y_pred=model.predict(X_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

In [29]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.88      0.93         8
           2       0.83      1.00      0.91         5

    accuracy                           0.97        30
   macro avg       0.94      0.96      0.95        30
weighted avg       0.97      0.97      0.97        30

[[17  0  0]
 [ 0  7  1]
 [ 0  0  5]]
